### ISSUE TITLE
Cringe

### ISSUE THREAD

**Issue by skashtanov** [F3T1W/CPP-Practice#1]
https://github.com/F3T1W/CPP-Practice/blob/d1b2a940ded34bb19884ad9431b36e28fd03a908/C6T1.cpp#L12

1. Не обязательно делать каст к char
2. Тернарный оператор можно внести напрямую в std::cout.
`std::cout << (islower(ch) ? toupper(ch) : tolower(ch));`

**Comment by F3T1W** [comment]
Done
