### ISSUE TITLE
Cringe 2

### ISSUE THREAD

**Issue by skashtanov** [F3T1W/CPP-Practice#2]
https://github.com/F3T1W/CPP-Practice/blob/d1b2a940ded34bb19884ad9431b36e28fd03a908/C6T2.cpp

1. Длина массива (10) повторяется много раз. В циклах лучше использовать либо 
    `for (double x: jija)` (для операций чтения) либо `for (double& x: jija)` для операций записи
2. `sum` уже имеет тип `double`, для деления на 10 не нужно приводить 10 к `double` явным кастом. Во всяком случае есть просто литерал `10.0`, который уже имеет тип `double`
3. Массив не инициализируется по умолчанию, а значит если у тебя произошел выход из цикла по `if (isalpha(jija[i])`, то во-первых в `jija` лежит уже буква, так как ты ее считал с `cin`, а во вторых, когда ты во втором цикле считаешь количество чисел выше среднего, то ты считаешь не то, что нужно, так как, все элементы, которые шли после `break` остались неициализированными и вполне могли быть равными нескольким миллионам. Для избежания такой ситуации у `std::array` есть метод `.fill` (заполнять для суммы, очевидно, нулями), который следовало вызвать до заполнения массива с консоли. 
4. Переменная называется `higherThanAverage`, но на деле там просто лежит `sum / n`, значит просто average, роль `higherThanAverage` выполняет `counter`.
5. `isalpha` принимает `int`, а считываешь ты `double`, значит при вызове `double` будет каститься к `int`
6. Принимать `void` как параметр функции бессмысленно, это то же самое, что не принять ничего
7. Название `DigitsOnly` неверное, так как оно по факту считает и ВЫВОДИТ какие - то значения, в зависимости от ввода с консоли. SRP нарушен, почему просто не принять массив в качестве параметра?
8. Поиск суммы и подсчет по условию давно есть в `std`, в 99% случаев стандартная библиотека работает лучше.
9. Ссылки на методы из 8:
`std::accumulate`: https://en.cppreference.com/w/cpp/algorithm/accumulate
`std::count_if`: https://en.cppreference.com/w/cpp/algorithm/count
10. Выводить в консоль не лучшее решение, даже если того просит условие задачи. Вернуть структурку с говорящими именами полей и потом ее запринтить - good.
11. Код
```
#include <iostream>
#include <array>
#include <numeric>
#include <algorithm>

const size_t N = 5;

struct Result {
    double Average;
    size_t HigherThanAverage;
};

void FillArray(std::array<double, N>& numbers) {
    for (double& x: numbers) {
        std::cin >> x;
    }
}

Result ComputeStats(const std::array<double, N>& numbers) {
    double average = std::accumulate(numbers.begin(), numbers.end(), 0.0) / N;
    size_t higherThanAverage = std::count_if(numbers.begin(), numbers.end(), [average](double x) {
        return x > average;
    });
    return { average, higherThanAverage };
}


int main() {
    std::array<double, N> numbers;
    FillArray(numbers);
    auto stats = ComputeStats(numbers);
    std::cout << stats.Average << ' ' << stats.HigherThanAverage;
    return 0;
}
```

**Comment by F3T1W** [comment]
Done
